Dev-env: Allow --multisite to accept boolean, subdirectory, or subdomain values
Automattic/vip pull request #1334
Opened 2023-04-14 20:20 UTC by rebeccahum

## Description

Allows for passing in `subdomain` or `subdirectory` into the `--multisite` parameter.  

## Steps to Test

1) `npm run build`
2) Create new sites with various command line `multisite` values:

```
./dist/bin/vip-dev-env-create.js --slug test1 --multisite subdomain --elasticsearch false --mailhog false --phpmyadmin false --wordpress 6.2 --app-code ~/vipdev/vip-go-skeleton --php 8.0 --xdebug false --title Test
```
```
./dist/bin/vip-dev-env-create.js --slug test2 --multisite subdirectory --elasticsearch false --mailhog false --phpmyadmin false --wordpress 6.2 --app-code ~/vipdev/vip-go-skeleton --php 8.0 --xdebug false --title Test
```
```
./dist/bin/vip-dev-env-create.js --slug test3 --multisite true --elasticsearch false --mailhog false --phpmyadmin false --wordpress 6.2 --app-code ~/vipdev/vip-go-skeleton --php 8.0 --xdebug false --title Test
```
```
./dist/bin/vip-dev-env-create.js --slug test4 --multisite false --elasticsearch false --mailhog false --phpmyadmin false --wordpress 6.2 --app-code ~/vipdev/vip-go-skeleton --php 8.0 --xdebug false --title Test
```
```
./dist/bin/vip-dev-env-create.js --slug test5 --multisite invalid --elasticsearch false --mailhog false --phpmyadmin false --wordpress 6.2 --app-code ~/vipdev/vip-go-skeleton --php 8.0 --xdebug false --title Test
```
Ensure values in the `instance_data.json` are valid (boolean, `"subdirectory"`, `"subdomain"`)
3) Repeat step 2 with prompt

2023-04-14 21:03 UTC, sjinks requested changes
Please see the comments above.

2023-04-14 21:03 UTC, sjinks commented on src/lib/dev-environment/dev-environment-cli.js
> +		multisite: preselectedOptions.multisite !== undefined ? resolveMultisite( preselectedOptions.multisite ) : await resolveMultisite( promptForTextBoolean( multisiteText, defaultOptions.multisite || D
Are you sure you have `await` in the proper place?

```js
? resolveMultisite(/**/) : await resolveMultisite(/**/),
```

We should have it either in both cases or nowhere.

I suspect that you meant this instead:
```suggestion
		multisite: preselectedOptions.multisite !== undefined ? resolveMultisite( preselectedOptions.multisite ) : resolveMultisite( await promptForTextBoolean( multisiteText, defaultOptions.multisite || DEV_ENVIRONMENT_DEFAULTS.multisite ) ),
```

2023-04-14 21:03 UTC, sjinks commented on src/lib/dev-environment/dev-environment-cli.js
> +		multisite: preselectedOptions.multisite !== undefined ? resolveMultisite( preselectedOptions.multisite ) : await resolveMultisite( promptForTextBoolean( multisiteText, defaultOptions.multisite || D
Also please note that ESLint complains:
> This line has a length of 243. Maximum allowed is 200

PS: if you are developing in VSCode, you may find this extension useful: [dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).

2023-04-14 21:05 UTC, rebeccahum commented on src/lib/dev-environment/dev-environment-cli.js
> +		multisite: preselectedOptions.multisite !== undefined ? resolveMultisite( preselectedOptions.multisite ) : await resolveMultisite( promptForTextBoolean( multisiteText, defaultOptions.multisite || D
Oh yes! That is what I meant

2023-04-16 05:28 UTC, sjinks approved these changes

2023-04-16 05:28 UTC, sjinks commented
@pschoffer could you please take a look as well?

2023-04-17 05:06 UTC, pschoffer requested changes
This some cool upgrade that we were missing. Thanks for working on it @rebeccahum !

I left few notes bellow.

2023-04-17 05:06 UTC, pschoffer commented on assets/dev-env.lando.template.yml.ejs
> -      - sh /dev-tools/setup.sh database root "http://<%= siteSlug %>.vipdev.lndo.site/" "<%= wpTitle %>" <% if ( multisite ) { %> <%= siteSlug %>.vipdev.lndo.site <% } %>
1) Is there a way to make this line multiline? this long line is quite tough to read.
2) Do you have PR for the `setup.sh` script? I think maybe we should introduce there an arg parser at this point. So that we can send in here `--subdomains` instead of 4th positional argument.

2023-04-17 05:06 UTC, pschoffer commented on src/lib/dev-environment/dev-environment-cli.js
> +export async function promptForTextBoolean( message: string, initial: string | boolean ): Promise<string | boolean> {
```suggestion
export async function promptForTextOrBoolean( message: string, initial: string | boolean ): Promise<string | boolean> {
```

2023-04-17 05:06 UTC, pschoffer commented on src/lib/dev-environment/dev-environment-cli.js
> +export function processStringBooleanOption( value: string | boolean ): string | boolean {
```suggestion
export function processStringOrBooleanOption( value: string | boolean ): string | boolean {
```

2023-04-17 05:06 UTC, pschoffer commented on src/lib/dev-environment/dev-environment-cli.js
>  	let multisiteText = 'Multisite';
The change from boolean prompt to string will mean omitting the `(y/N)` from the message. Shall we add it here? I am not sure if e want to though  having something like `(y/N/subdirectory/subdomain)` feels wrong :) 

So maybe we can leave it as it is. 

What do you think?

2023-04-17 05:06 UTC, pschoffer commented on src/lib/dev-environment/dev-environment-cli.js
> +		multisite: resolveMultisite( preselectedOptions.multisite ?? await promptForTextBoolean( multisiteText, defaultOptions.multisite || DEV_ENVIRONMENT_DEFAULTS.multisite ) ),
We currently don't seem to be doing any validation of the imput from user.

I tested it and it takes in the `banana` for multisite and turns it into `false`.

I think what we should do instead is go through similar re-prompting as we do if you provide an incorrect path to client-code or mu-plugins.

Also there we can list all the valid options properly without making the first prompt heavy to read.

![image](https://user-images.githubusercontent.com/19240162/232383392-b95fc4ca-7b36-4ed7-9f19-e03916852d24.png)

2023-04-17 17:52 UTC, rebeccahum commented on src/lib/dev-environment/dev-environment-cli.js
>  	let multisiteText = 'Multisite';
I think we can leave as-is if we add a validator down below 🙂

2023-04-17 19:36 UTC, rebeccahum commented on src/lib/dev-environment/dev-environment-cli.js
> +export async function promptForTextBoolean( message: string, initial: string | boolean ): Promise<string | boolean> {
I ended up changing this to `promptForMultisite` with the validation we added

2023-04-17 19:40 UTC, rebeccahum commented on assets/dev-env.lando.template.yml.ejs
> -      - sh /dev-tools/setup.sh database root "http://<%= siteSlug %>.vipdev.lndo.site/" "<%= wpTitle %>" <% if ( multisite ) { %> <%= siteSlug %>.vipdev.lndo.site <% } %>
Done, here's the corresponding https://github.com/Automattic/vip-container-images/pull/466

2023-05-29 15:09 UTC, sjinks approved these changes

2023-05-29 15:10 UTC, merged