[dev-env] Tweak error handling dev-env sync
Automattic/vip pull request #1414
Opened 2023-06-21 12:25 UTC by pschoffer

## Description

* Unifies boolean parsing logic in exec
* Adds `--force` to dev-env sync sql to avoid check if environment is up or not
* Adds check for slug presence to replace "Contact customer support" - type of error into "Use '--slug' ..." - type

## Steps to Test

1. Check out PR.
1. Run `npm run build`
1. Run `./dist/bin/vip-dev-env-sync-sql.js` 
1. Should instruct you to provide env name.

2023-06-21 21:56 UTC, rinatkhaziev commented on src/bin/vip-dev-env-sync-sql.js
> +	.option( 'force', 'Disabling validations before task execution', undefined, processBooleanOption )
```suggestion
	.option( 'force', 'Disable validations before task execution', undefined, processBooleanOption )
```

2023-06-27 02:08 UTC, rinatkhaziev requested changes
I think using `present simple` would be more appropriate that `ing`,`Suppress output` and `Disable validation before task execution` sound more "natural" in the context of CLI commands.

2023-06-28 08:22 UTC, pschoffer commented
Thanks @rinatkhaziev

2023-07-18 12:20 UTC, sjinks approved these changes

2023-07-18 14:15 UTC, merged