Add/media import improvements
Automattic/vip pull request #1827
Opened 2024-05-09 05:30 UTC by ariskataoka

## Description

This PR uses the failure details URL for the import media command. 

## Pull request checklist

- [ ] Update [SETUP.md](https://github.com/Automattic/vip-cli/blob/trunk/docs/SETUP.md#list-of-environmental-variables) with any new environmental variables.
- [ ] Update [the documentation](https://github.com/Automattic/vip-cli/blob/trunk/docs).
- [ ] [Manually test](https://github.com/Automattic/vip-cli/blob/trunk/docs/TESTING.md#manual-testing) the relevant changes.
- [ ] Follow the [pull request checklist](https://github.com/Automattic/vip-cli/blob/trunk/docs/RELEASING.md#new-pull-requests)
- [ ] Add/update [automated tests](https://github.com/Automattic/vip-cli/blob/trunk/docs/TESTING.md#automated-testing) as needed.

## New release checklist

- [ ] [Automated tests](https://github.com/Automattic/vip-cli/blob/trunk/docs/TESTING.md#automated-testing) pass.
- [ ] The [Preparing for release checklist](https://github.com/Automattic/vip-cli/blob/trunk/docs/RELEASING.md#preparing-for-release) is completed.

## Changelog Description

Media import: Add option to download failure details logs from URL returned in the media import request response body. 

## Steps to Test

**Obs.:** This test requires a locall VIP API  public up and running. 

1. Check out PR.
1. Run `npm run build`

### Scenario 1:

1. Import media files by running `  VIP_PROXY="" API_HOST={ LOCAL_VIP_API_PUBLIC_URL } node ./dist/bin/vip-import-media.js @{ TEST_SITE_ID }.{ ENV_SITE } { MEDIA_TO_BE_IMPORTED_URL }`

The output should contain a message about the errors and a prompt as:
```
⚠️  Error details can be found on ${ ERROR_DETAILS_URL_RETURNED_BY_VIP_PUBLIC_API }
Download error details now? (y/N) › 
```

1. Answer y
2. The output should contain information about the download and the local file as a result:

```
⚠️  All errors have been exported to { LOCAL_PATH }
```

### Scenario 2:

Repeat step 1 
1. Answer n
2. The prompt should exit

2024-05-13 06:24 UTC, t-wright commented on src/lib/media-import/status.ts
> +Downloading errors details from ${ fileErrorsUrl }...
```suggestion
Downloading errors details from ${ fileErrorsUrl } ...
```

Currently ellipsis is treated as part of the URL which breaks the presigned URL

2024-05-17 09:50 UTC, sjinks requested changes

2024-05-17 09:50 UTC, sjinks commented on package.json
> +  "version": "2.40.0-dev.2",
Please don't do this. The [prepare release workflow](https://github.com/Automattic/vip-cli/actions/workflows/npm-prepare-release.yml) updates the package version.

2024-05-17 09:50 UTC, sjinks commented on npm-shrinkwrap.json
> +  "version": "2.40.0-dev.2",
Same as above

2024-05-17 09:50 UTC, sjinks commented on npm-shrinkwrap.json
> +      "version": "2.40.0-dev.2",
Same as above

2024-06-05 06:25 UTC, merged