[dev-env] support windows db import
Automattic/vip pull request #894
Opened 2021-10-21 15:18 UTC by pschoffer

## Description

When trying to import on Windows machine - `vip dev-env imposrt sql \Users\<user>\dump.sql` we encounter an error resolving the path. Due to the way this works we need to construct in container path to the import file which doesn't work if `\` instead of `/` are systems path separators.

This change does the manual conversion of `\` to `/` to address that.

One note there is a limitation due to the way the file is processed that the file needs to be under home directory. I will try to document that more in public docs.

## Steps to Test

Example:

1. Downgrade to Windows
1. Run `vip dev-env import sql <path to file>`
2. It works

2021-10-22 08:40 UTC, pauarge requested changes
Changes look great, left a couple of nit-picky suggestions.

Also, I think it would be worth adding an additional unit test that covers the Windows case.

2021-10-22 08:40 UTC, pauarge commented on src/lib/dev-environment/dev-environment-core.js
> +
```suggestion
	/**
	 * Docker container does not have acces to the host filesystem.
	 * However lando maps os.homedir() to /user in the container. So if we replace the path in the same way
	 * in the Docker container will get the file from within the mapped volume under /user.
	 */
```

2021-10-22 08:40 UTC, pauarge commented on src/lib/dev-environment/dev-environment-core.js
> +		// Because the file path generated for windows will have \ instead of / we need to replace that as well so that the path inside the container (unix) still works.
```suggestion
		// Because the file path generated for Windows will have \ instead of / we need to replace that so that the path inside the container (Linux) still works.
```

2021-10-25 07:04 UTC, pschoffer commented
How's this @pauarge ?

2021-10-25 07:24 UTC, pauarge approved these changes
Looks great, thanks for adding the tests!

2021-10-25 07:26 UTC, merged