[dev-env] Delete file permissions
Automattic/vip pull request #902
Opened 2021-10-27 12:08 UTC by pschoffer

## Description

This change:
* simplifies the lando file creation
* Uses new images for mu-plugins and dev-tools
* Combined with that above some other tweaks to make sure files will be own by the current user

## Steps to Test

1) Create env
2) Start env
3) Do some stuff
4) Restart env
5) Delete env

__no errors anywhere__

2021-10-27 14:13 UTC, pauarge requested changes
Looking good, left a couple of questions.

2021-10-27 14:13 UTC, pauarge commented on assets/dev-env.lando.template.yml.ejs
> +      image: ghcr.io/automattic/vip-container-images/mu-plugins:0.1
mu-plugins should always be `latest`, given it's always-updating nature

2021-10-27 14:13 UTC, pauarge commented on src/lib/constants/dev-environment.js
>  	},
If the three are 'image', we might simplify this and specify nothing?

2021-10-28 06:32 UTC, pschoffer commented on assets/dev-env.lando.template.yml.ejs
> +      image: ghcr.io/automattic/vip-container-images/mu-plugins:0.1
Well not really. The mu-plugins code will be self updating but the containe itself has some other scripts and structure that I would like to start version. Here - https://github.com/Automattic/vip-container-images/pull/35 - we changed both how the docker entrypoint `run.sh` (that was unused up till now) and autoupdating works (it didn't before).

If we in the future would like to introduce some breaking change say change the folder that contains the autoupdated code from `/shared` to `/mu-plugins` we would like to NOT break all the dev-envs in the wild already expecting the folder to be `/shared`.

2021-10-28 06:45 UTC, pschoffer commented on src/lib/constants/dev-environment.js
>  	},
Oh yeah! We dont use those anymore.

2021-10-28 07:09 UTC, pauarge approved these changes

2021-10-28 07:29 UTC, merged